---
# tasks file for opencv install
- name: opencv git clone with specific checkout
  git:
    repo: https://github.com/opencv/opencv.git
    dest: /opt/opencv
    version: "{{opencv_version}}"

- name: opencv_contrib git clone with specific checkout
  git:
    repo: https://github.com/opencv/opencv_contrib.git
    dest: /opt/opencv_contrib
    version: "{{opencv_version}}"

- name: Install compiler
  apt: name={{item}} update_cache=yes
  with_items:
    - build-essential

- name: Install required
  apt: name={{item}} update_cache=yes
  with_items:
    - cmake
    - git
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libv4l-dev
    - unzip

- name: Install optional
  apt: name={{item}} update_cache=yes
  with_items:
    - python-dev
    - python-numpy
    - python3-dev
    - python3-numpy
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - libtiff5-dev
    - libpng12-dev
    - libgtk2.0-dev
    - libatlas-base-dev
    - gfortran

- name: Creates directory for build
  file: path=/opt/opencv/release state=directory

- name: cmake for opencv
  shell: cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv_contrib/modules ..
  args:
    chdir: /opt/opencv/release

- name: get cores for make
  shell: nproc
  register: num_cores

- name: make for opencv
  shell: make -j{{num_cores.stdout}}
  args:
    chdir: /opt/opencv/release

- name: make install for opencv
  shell: make install
  args:
    chdir: /opt/opencv/release
