---
# tasks file for caffe install

- name: extract caffe in library_path
  unarchive: src="{{comp}}" dest="{{library_path}}"

- name: get the username running the deploy
  local_action: command whoami
  register: username

- name: Download default version
  get_url:
    dest: '{{library_path}}/{{caffe_file_name}}'
    mode: 0755
    owner: "{{username.stdout}}"
    group: "{{username.stdout}}"
    url: "{{caffe_file_url}}"

- name: extract caffe in library_path
  unarchive: src={{comp}} dest={{library_path}}

- name: install python dependencies
  shell: "for req in $(cat requirements.txt); do pip install $req --upgrade; done"
  args:
    chdir: '{{library_path}}/caffe-{{caffe_version}}/python'

- name: update python-dateutil
  shell: pip install python-dateutil --upgrade

- name: Creates directory for build
  file: path='{{library_path}}/caffe-{{caffe_version}}/release' state=directory

- name: cmake for caffe
  shell: cmake -D python_version=3 ..
  args:
    chdir: '{{library_path}}/caffe-{{caffe_version}}/release'

- name: get cores for make
  shell: nproc
  register: num_cores

- name: make for caffe
  shell: make all -j{{num_cores.stdout}}
  args:
    chdir: '{{library_path}}/caffe-{{caffe_version}}/release'

- name: make pycaffe
  shell: make pycaffe
  args:
    chdir: '{{library_path}}/caffe-{{caffe_version}}/release'

