---
# tasks file for caffe install
- name: caffe git clone with specific checkout
  git:
    repo: https://github.com/BVLC/caffe.git
    dest: /opt/caffe
    version: "{{caffe_version}}"

- name: Install general dependencies
  apt: name={{item}} update_cache=yes
  with_items:
    - libprotobuf-dev 
    - libleveldb-dev
    - libsnappy-dev
    - libhdf5-serial-dev
    - protobuf-compiler

- name: Install atlas
  apt: name=libatlas-base-dev update_cache=yes

- name: Check for opencv
  stat: path=/usr/local/lib/libopencv_core.so
  register: cv_check

- name: Install opencv
  apt: name=libopencv-dev update_cache=yes
  when: not cv_check.stat.exists

- name: Install boost
  apt: name=libboost-all-dev install_recommends=no update_cache=yes

- name: Install python
  apt: name=python-dev update_cache=yes

- name: Remaining dependencies
  apt: name={{item}} update_cache=yes
  with_items:
    - libgflags-dev
    - libgoogle-glog-dev
    - liblmdb-dev

- name: python requeriments
  shell: for req in $(cat /opt/caffe/python/requirements.txt); do pip3 install $req; done

- name: python upgrade dateutils
  shell: pip3 install python-dateutil --upgrade

- name: symlinks for caffe in python3
  file:
    src: '/usr/lib/x86_64-linux-gnu/{{ item.src }}'
    dest: '/usr/lib/x86_64-linux-gnu/{{ item.dest }}'
    state: link
  with_items:
    - { src: 'libboost_python-py34.so', dest: 'libboost_python3.so' }
    - { src: 'libhdf5_serial.so.8.0.2', dest: 'libhdf5.so' }
    - { src: 'libhdf5_serial_hl.so.8.0.2', dest: 'libhdf5_hl.so' }

- name: copy Makefile.config with the new configuration to caffe folder
  copy:
    src: /etc/ansible/extra-config/caffe/Makefile.config
    dest: /opt/caffe
    owner: root
    group: root
    mode: 0755

- name: get cores for make
  shell: nproc
  register: num_cores

- name: make for caffe
  shell: make all -j{{num_cores.stdout}}
  args:
    chdir: /opt/caffe

- name: make pycaffe
  shell: make pycaffe
  args:
    chdir: /opt/caffe
